id: 261c457c-b92a-4ad6-8927-2aaa53c28ad3
version: 3
vcShouldKeepItemLegacyProdMachine: false
name: TestIPQualityScorePlaybook
description: This playbook tests the functionality of the IPQualityScore Integration
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: ca29acc5-6a2a-4111-8a15-c440abb3bacc
    type: start
    task:
      id: ca29acc5-6a2a-4111-8a15-c440abb3bacc
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "1"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "1":
    id: "1"
    taskid: fe9fec53-0320-4e67-84b2-f0956399ea25
    type: regular
    task:
      id: fe9fec53-0320-4e67-84b2-f0956399ea25
      version: -1
      name: DeleteContext
      description: Delete field from context
      scriptName: DeleteContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "2"
    scriptarguments:
      all:
        simple: "yes"
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 195
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "2":
    id: "2"
    taskid: ed2cb426-78b0-4886-83fb-1364e2c909c8
    type: regular
    task:
      id: ed2cb426-78b0-4886-83fb-1364e2c909c8
      version: -1
      name: ip
      description: Runs reputation on IPs.
      script: IPQualityScore|||ip
      type: regular
      iscommand: true
      brand: IPQualityScore
    nexttasks:
      '#none#':
      - "3"
    scriptarguments:
      ip: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 370
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "3":
    id: "3"
    taskid: 34c93603-762f-487d-8a54-0c77117759e2
    type: condition
    task:
      id: 34c93603-762f-487d-8a54-0c77117759e2
      version: -1
      name: Verify Output
      description: Verify context data set by the previous command.
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "5"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isNotEmpty
          left:
            value:
              simple: IP.Address
            iscontext: true
    view: |-
      {
        "position": {
          "x": 50,
          "y": 545
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "4":
    id: "4"
    taskid: 54bed444-3e47-480a-8c75-082897e1ed13
    type: title
    task:
      id: 54bed444-3e47-480a-8c75-082897e1ed13
      version: -1
      name: End
      type: title
      iscommand: false
      brand: ""
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1420
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "5":
    id: "5"
    taskid: 8d546a51-f6cf-4b95-8f29-0a9bcb3caa9f
    type: regular
    task:
      id: 8d546a51-f6cf-4b95-8f29-0a9bcb3caa9f
      version: -1
      name: email
      description: Runs reputation on email addresses.
      script: IPQualityScore|||email
      type: regular
      iscommand: true
      brand: IPQualityScore
    nexttasks:
      '#none#':
      - "6"
    scriptarguments:
      email: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 720
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "6":
    id: "6"
    taskid: 58acd708-f4d0-4f01-801a-465433e31b61
    type: condition
    task:
      id: 58acd708-f4d0-4f01-801a-465433e31b61
      version: -1
      name: Verify Output
      description: Verify context data set by the previous command.
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "7"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isNotEmpty
          left:
            value:
              simple: IPQualityScore.Email.address
            iscontext: true
    view: |-
      {
        "position": {
          "x": 50,
          "y": 895
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "7":
    id: "7"
    taskid: 4b317a91-aca6-4226-83b3-3621e646c0dd
    type: regular
    task:
      id: 4b317a91-aca6-4226-83b3-3621e646c0dd
      version: -1
      name: url
      description: Runs reputation on URLs.
      script: IPQualityScore|||url
      type: regular
      iscommand: true
      brand: IPQualityScore
    nexttasks:
      '#none#':
      - "8"
    scriptarguments:
      url: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1070
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "8":
    id: "8"
    taskid: 4149de9a-e30f-4c5f-8563-58325063fda7
    type: condition
    task:
      id: 4149de9a-e30f-4c5f-8563-58325063fda7
      version: -1
      name: Verify Output
      description: Verify context data set by the previous command.
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "4"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isNotEmpty
          left:
            value:
              simple: IPQualityScore.Email.address
            iscontext: true
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1245
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1435,
        "width": 380,
        "x": 50,
        "y": 50
      }
    }
  }
inputs: []
outputs: []
fromversion: 5.0.0
